homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 94
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/New_York
  #
  customize: !include_dir_merge_named customize 

# Show links to resources in log and frontend
#introduction:

# Zones
zone:
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  radius: 20
  icon: mdi:account-multiple

# Enables the frontend
frontend:

http:
  # Uncomment this to add a password (recommended!)
    api_password: !secret api_password
    ssl_certificate: !secret ssl_cert
    ssl_key: !secret ssl_key
    trusted_networks:
      - 127.0.0.1
      - 192.168.1.133
      - 192.168.1.39

# Checks for available updates
updater:

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

# Kodi
media_player:
  - platform: kodi
    host: http://192.168.1.133
    port: 8072
    username: !secret kodi_user
    password: !secret kodi_pass

# Mosquitto MQTT Broker
mqtt:
  broker: 192.168.1.133
  port: 1883
  client_id: home-assistant-1
  keepalive: 60

# IFTTT
ifttt:
  key: !secret ifttt_key

#  Groups - Display Stuff
group: !include groups.yaml
#group: !include_dir_merge_named group

alexa: !include alexa.yaml

# Automation
automation: !include_dir_list automation

device_tracker: !include device-tracker.yaml

logger:
  default: warn #I believe this is the default setting anyways?
  logs:
    homeassistant.components.device_tracker.asuswrt: error
    homeassistant.components.device_tracker.mqtt: debug

# Notifications
notify: !include notify.yaml

# Sensors
sensor: !include_dir_merge_list sensors

# Switches
#  Switches are anything (hardware or software) that can turn
#  on or off.
switch: !include_dir_merge_list switches

# Weblinks
weblink: !include weblink.yaml